sudo: required
language: node_js
services:
  - docker
node_js:
  - '8'
cache:
  directories:
    - ~/.npm
    - node_modules
  yarn: true
notifications:
  email: false
branches:
  only:
    - master
    - /^greenkeeper.*$/
before_install:
  # package-lock.json was introduced in npm@5
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g github-label-sync greenkeeper-lockfile
install:
  - travis_retry ./run --install
stages:
  - before
  - test
  - after
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: before
      name: 'Greenkeeper lockfile update'
      script: greenkeeper-lockfile-update
    - name: 'Repository Checks'
      script:
        - commitlint-travis
        - travis_retry github-label-sync -a "$GH_TOKEN" -l 'https://git.io/fAe5i' seantrane/stshell
    - stage: test
      name: 'Lint Analysis'
      script: ./run --lint
    - name: 'Testing and Reporting'
      script: ./run --test --report
    - stage: after
      name: 'Greenkeeper lockfile upload'
      script: greenkeeper-lockfile-upload
    - stage: deploy
      name: 'Publish'
      script: ./run --publish
