sudo: false
language: node_js
node_js:
  - 8
cache:
  directories:
    - ~/.npm
    - node_modules
  yarn: true
notifications:
  email: false
branches:
  only:
    - master
    - /^greenkeeper.*$/
install:
  - travis_retry yarn install
script:
  - "echo \"Skipping build/tests.\""
after_success:
  - npm run semantic-release
