#!/usr/bin/env bash
#
# Determine size of a file or total size of a directory

fs () {

  local arg=-sh

  if du -b /dev/null > /dev/null 2>&1; then
    arg=-sbh
  fi

  # shellcheck disable=SC2199
  if [[ -n "$@" ]]; then
    du $arg -- "$@"
  else
    # shellcheck disable=SC2035
    du $arg .[^.]* *
  fi

}
